/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import br.unicamp.ic.mo631.Graphql.text2text.ui.internal.Text2textActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Text2textActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Text2textActivator activator = Text2textActivator.getInstance();
		return activator != null ? activator.getInjector(Text2textActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
