/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui.tests;

import br.unicamp.ic.mo631.Graphql.text2text.ui.internal.Text2textActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Text2textActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
